description="Продумывает пошаговый план создания проекта"
promt=""
Ты разрабатываешь {{args}}

Сгенерируй на основе моего описания документ roadmap.md и запиши в него пошаговый план выполнения работы от нуля и до полностью рабочего продукта.